Repository SimonCahill/getopt.net, pull requests merged in 2023-02, with the labels that each got.

#10 Support earlier versions of .NET.
  getopt.net/GetOpt.cs
  getopt.net/getopt.net.csproj
Labels: enhancement

#12 Corrected behavior when non-option arguments are encountered.
  getopt.net.tests/GetOptTests.cs
  getopt.net.tests/GetOptTests_Inherited.cs
  getopt.net.tests/GetOptTests_RealWorld.cs
  getopt.net/GetOpt.cs
  getopt.net/getopt.net.csproj
Labels: bug, enhancement

#14 Enable double dash stops parsing by default
  CHANGELOG.md
  getopt.net.sln
  getopt.net.tests/GetOptTests_RealWorld.cs
  getopt.net.tests/getopt.net.tests.csproj
  getopt.net/GetOpt.cs
  getopt.net/Option.cs
  getopt.net/getopt.net.csproj
Labels: enhancement

#16 Added reference implementations in both VB and C#
  getopt.net.reference.cs/Program.cs
  getopt.net.reference.cs/getopt.net.reference.cs.csproj
  getopt.net.reference.vb/My Project/launchSettings.json
  getopt.net.reference.vb/Program.vb
  getopt.net.reference.vb/getopt.net.reference.vb.vbproj
  getopt.net.sln
Labels: documentation, enhancement

#19 Removed support for Option.Flag
  README.md
  getopt.net.tests/GetOptTests_RealWorld.cs
  getopt.net/Option.cs
  getopt.net/getopt.net.csproj
Labels: documentation, enhancement
